name: Carly Zien
markdown: redcarpet
pygments: true
permalink: pretty
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: false   # true|false